version: "3.9"
services:
  frontend:
    build: 
      context: ./gipfeli-frontend
      args:
        - REACT_APP_STORAGE_BUCKET_BASE_URL=${REACT_APP_STORAGE_BUCKET_BASE_URL}
        - REACT_APP_PUBLIC_BACKEND_API=${REACT_APP_PUBLIC_BACKEND_API}
        - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN:-}
        - REACT_APP_SENTRY_ENVIRONMENT=${REACT_APP_SENTRY_ENVIRONMENT:-}
    ports:
      - "3001:8080"

  backend:
    build: ./gipfeli-api
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - ./gipfeli-api/.env
    command: 
      - /bin/sh
      - -c
      - |
        echo "Waiting 15s so our db has started"
        sleep 15s
        npm run typeorm:migrate
        npm run start:prod

  database:
    image: postgis/postgis:14-3.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 3002:8080