version: "3.9"
services:
  frontend:
    build: ./gipfeli-frontend
    env_file:
      - ./gipfeli-frontend/.env
    ports:
      - "9999:8080"
  backend:
    build: ./gipfeli-api
    depends_on:
      - database
    env_file:
      - ./gipfeli-api/.env
  database:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080