version: "3.9"
services:
  frontend:
    build: 
      context: ./gipfeli-frontend
      args:
        - PUBLIC_BACKEND_API=http://backend:3000
    env_file:
      - ./gipfeli-frontend/.env
    ports:
      - "9999:8080"
  backend:
    build: ./gipfeli-api
    depends_on:
      - database
    env_file:
      - ./gipfeli-api/.env
    command: 
      - /bin/sh
      - -c
      - |
        echo "Waiting 15s so our db has started"
        sleep 15s
        npm run typeorm:migrate
        npm run start:prod
  database:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080