version: "3.9"
services:
  frontend:
    container_name: gipfeli_frontend
    build: ./gipfeli-frontend
    env_file:
      - ./gipfeli-frontend/.env
    ports:
      - "3001:8080"

  backend:
    container_name: gipfeli_api
    build: ./gipfeli-api
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - ./gipfeli-api/.env
    command: 
      - /bin/sh
      - -c
      - |
        echo "Waiting 15s so our db has started"
        sleep 15s
        npm run typeorm:migrate
        npm run start:prod

  database:
    container_name: gipfeli_db
    image: postgis/postgis:14-3.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    container_name: gipfeli_adminer
    image: adminer
    restart: always
    ports:
      - 3002:8080